apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-label-injector
webhooks:
  - name: webhook.webhook-system.svc
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - webhook-system
    clientConfig:
      service:
        name: webhook
        namespace: webhook-system
        path: /mutate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqekNDQW5lZ0F3SUJBZ0lVWjcxdFF3dklXQnZJSktzK1dlUmdhODRTVytjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pURWpNQ0VHQTFVRUF3d2FkMlZpYUc5dmF5NTNaV0pvYjI5ckxYTjVjM1JsYlM1emRtTXdIaGNOTWpVdwpOakkyTURRME56UXpXaGNOTWpZd05qSTJNRFEwTnpReldqQWxNU013SVFZRFZRUUREQnAzWldKb2IyOXJMbmRsClltaHZiMnN0YzNsemRHVnRMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUIKQUpxbmV5Q2lzVkFpNVRKN2dQRWNmbkNwVGk3ZWdLQUQ3UlJnUWhxci9oZUQ5NW1Pd3RqTG9HWDVKcCtWWDh4dQpTcEpjemp5YmVJN3VySTcyUFIzQ3MvcjZWcldkbXdrbllidkVESDlkZWgwbnhOdUV3dEhxeUE4SDQrdnc0Wm5qCkF1Nm9mODZVdHFLU1RpNXhmZVhsUUhFSEJMUFVPQUNpNTJsNEhISFY3UTFHeXJ3TVpLQnFaTHhaTHhPWmIrZW0KaEl4WUMrMmNoZmZPL0pUNWZNS2NwOWVsUXdLbXF2VnBtcHBTd0FQVVZlb2ZPUnRSRCt1TkpJN0dabEx4T0pIKwphRXlRd0YwdW14Zzdld0dPMGY5dW9MamFha2J6MHAxK29yNDNWaVF0eUg0Uk82YXR0VjVvb3VqeUZOQzFSTFNWCjNpc2RnNmhkMnM1WkYvQnJIUjhTQVNjQ0F3RUFBYU9CdGpDQnN6QUxCZ05WSFE4RUJBTUNCREF3RXdZRFZSMGwKQkF3d0NnWUlLd1lCQlFVSEF3RXdjQVlEVlIwUkJHa3daNElIZDJWaWFHOXZhNElXZDJWaWFHOXZheTUzWldKbwpiMjlyTFhONWMzUmxiWUlhZDJWaWFHOXZheTUzWldKb2IyOXJMWE41YzNSbGJTNXpkbU9DS0hkbFltaHZiMnN1CmQyVmlhRzl2YXkxemVYTjBaVzB1YzNaakxtTnNkWE4wWlhJdWJHOWpZV3d3SFFZRFZSME9CQllFRkhxNVpBOU8KK1p0Y0U0T1NXOFRQUTlBZ25mQ0VNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJpSmthUkxSQll5akhqTjc1bgpQdFBJMGZpcVVabFBPNkw5WjhMbTdBMm5hekxQWnQ1d3BIdFhLQmM4N0FDdUdCTUhEbU84cmdGZHIwM21BSjRKCllNWGNDVWo2ZmRYSTB5L2NtZTFNdFFLeWt6THVCVmlWY25hYmZVS2MyRVRWcGVDZ20vN0RyZXZaeEtJdHZ4R2YKQTRVd2oyQ3pndnROTE04elVMbXN1ZVZhK1FKLy9OQmwwb0hCYU1tR2daZmxmSzdlY3k1aTkvZTFPZHduSkR4MQpscWlRRTV0dmdkUVk0aEF0eU44ZnMyWTBSK3VIR3hJcFp3QTFDR2ZVOWw3SExDMndUYkxTbVNOQlllVVpqM0FqClBKZGxFZmtsNFRWMmNkZk5DZkhVMWdOSUNZME9yWTVLdzF1RDJOa3hwUllxQms2SDkvZ2p5VDV2VldkeU1pWGkKQXdRcwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
